### ISSUE TITLE
2-d hist plot plots all versions of processing

### ISSUE THREAD

**Issue by jeanconn** [sot/vv_trending#1]
The 2-d hist plot is current overplotting/binning all processed versions (that have run through our mica vv processing).  Should it do this?  I think we had this discussion before, but I can't find my notes.  I'm just not sure if we want it to show:
- all version overplotted/binned
- just the first processed data 
- just the default/released data

I think the last one (default/released) would be fine for our purposes, but not sure.  @taldcroft?

**Comment by taldcroft** [comment]
I am never interested in anything but the released version.

**Comment by jeanconn** [comment]
OK!  Also then, should the plot include residuals for dropped stars or not?  The histogram scale is fixed, so even though they are "plotted" we're losing some of them off the top of the plot.

**Comment by taldcroft** [comment]
Interesting question.  One version tells us about what's happening on the spacecraft, the other about ground processing and science data.  Maybe we need both, but at SSAWG we'd look at the spacecraft version.

**Comment by jeanconn** [comment]
Though for "spacecraft" should we calc against osol and use the obc flags
on stars and such in that version?

**Comment by jeanconn** [comment]
Closed by 7101513bb1897136d3c11fc06e7a550f990427b4 which sets the 2d plot to only used the default data.
